"""empty message

Revision ID: 0f8bc241d454
Revises: c15bfd2e8cf3
Create Date: 2023-02-01 17:56:33.680596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8bc241d454'
down_revision = 'c15bfd2e8cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('country_code', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'country_code')
    # ### end Alembic commands ###
