"""empty message

Revision ID: 314714ea816a
Revises: add09971c49d
Create Date: 2023-02-24 15:56:13.393198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314714ea816a'
down_revision = 'add09971c49d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('account', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'account')
    # ### end Alembic commands ###
