"""empty message

Revision ID: 58a334f995c8
Revises: 67a3b59ddf44
Create Date: 2023-02-18 14:44:09.082439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a334f995c8'
down_revision = '67a3b59ddf44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'property', 'category', ['category_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property', type_='foreignkey')
    op.drop_column('property', 'category_id')
    # ### end Alembic commands ###
