"""empty message

Revision ID: 58cd7a33a5dd
Revises: 0a4a778e3119
Create Date: 2023-02-18 16:32:09.854734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58cd7a33a5dd'
down_revision = '0a4a778e3119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('host_language', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'host_language')
    # ### end Alembic commands ###
