"""empty message

Revision ID: 616a6174d218
Revises: 82039c111e3f
Create Date: 2023-02-03 15:12:08.606072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616a6174d218'
down_revision = '82039c111e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'property', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property', type_='foreignkey')
    op.drop_column('property', 'user_id')
    # ### end Alembic commands ###
