"""empty message

Revision ID: 6dfc9a99ef6b
Revises: 1b0918292029
Create Date: 2023-02-03 16:43:17.303074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfc9a99ef6b'
down_revision = '1b0918292029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('created_at', sa.Date(), nullable=True))
    op.add_column('review', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'updated_at')
    op.drop_column('review', 'created_at')
    # ### end Alembic commands ###
