"""empty message

Revision ID: 7c667be9e106
Revises: 58cd7a33a5dd
Create Date: 2023-02-18 16:44:28.917222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c667be9e106'
down_revision = '58cd7a33a5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('type_of_property', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'type_of_property')
    # ### end Alembic commands ###
