"""empty message

Revision ID: 82039c111e3f
Revises: b2a4b47ca8d3
Create Date: 2023-02-03 12:58:15.231913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82039c111e3f'
down_revision = 'b2a4b47ca8d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('social_id', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('social_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'social_type')
    op.drop_column('user', 'social_id')
    # ### end Alembic commands ###
