"""empty message

Revision ID: 8f307a451fcf
Revises: 
Create Date: 2023-02-08 18:22:43.541668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f307a451fcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'latitude')
    op.drop_column('property', 'longitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('longitude', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('property', sa.Column('latitude', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
