"""empty message

Revision ID: 902a90291522
Revises: b9e5ee8033df
Create Date: 2023-02-08 19:16:55.146658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902a90291522'
down_revision = 'b9e5ee8033df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('status', sa.Enum('pending', 'upcoming', 'active', 'completed', name='status'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'status')
    # ### end Alembic commands ###
