"""empty message

Revision ID: add09971c49d
Revises: 3fbcd6ef0e31
Create Date: 2023-02-23 17:00:17.528728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add09971c49d'
down_revision = '3fbcd6ef0e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('customer_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'customer_id')
    # ### end Alembic commands ###
