"""empty message

Revision ID: b2a047601d5d
Revises: 95c44edb91ea
Create Date: 2023-02-24 19:04:44.010089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a047601d5d'
down_revision = '95c44edb91ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_info', sa.Column('booking_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payment_info', 'booking', ['booking_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_info', type_='foreignkey')
    op.drop_column('payment_info', 'booking_id')
    # ### end Alembic commands ###
