"""empty message

Revision ID: b2a4b47ca8d3
Revises: 763992b44a48
Create Date: 2023-02-02 19:40:01.616547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a4b47ca8d3'
down_revision = '763992b44a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('bathrooms', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'bathrooms')
    # ### end Alembic commands ###
