"""empty message

Revision ID: b9e5ee8033df
Revises: c4752efa2b5f
Create Date: 2023-02-08 19:16:42.682800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9e5ee8033df'
down_revision = 'c4752efa2b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('status', mysql.VARCHAR(length=1), nullable=True))
    # ### end Alembic commands ###
