"""empty message

Revision ID: d7a16f7adfb8
Revises: 
Create Date: 2023-02-01 17:52:07.072541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a16f7adfb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=True),
    sa.Column('phone_no', sa.String(length=15), nullable=True),
    sa.Column('country_code', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=True),
    sa.Column('photo_name', sa.String(length=225), nullable=True),
    sa.Column('is_block', sa.Boolean(), nullable=True),
    sa.Column('device_id', sa.String(length=300), nullable=True),
    sa.Column('device_type', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
