"""empty message

Revision ID: e1c03fec8591
Revises: 231457bcc365
Create Date: 2023-02-24 18:42:18.039143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c03fec8591'
down_revision = '231457bcc365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_info', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('payment_info', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_info', 'updated_at')
    op.drop_column('payment_info', 'created_at')
    # ### end Alembic commands ###
